
[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[prune]
  go-tests = true
  unused-packages = true

# Fix: vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
branch = "master"